name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO111MODULE: on

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.13, 1.14, 1.15, 1.16]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - uses: golangci/golangci-lint-action@v2

      - name: Run Tests
        run: |
          go test -race --coverprofile=coverage.coverprofile --covermode=atomic ./...

      - name: Run generates
        run: |
          sh test.sh

      - name: Upload coverage to Codecov
        if: success() && matrix.go == 1.13 && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --dry-run
